### ISSUE TITLE
Update for 1.17

### ISSUE THREAD

**Issue by frozenwarrior41** [jsnimda/Inventory-Profiles#56]
love the mod but i am not skilled enough to figure out how to get this updated for 1.17 as it constantly crashes upon launching the game

**Comment by badcodebuilder** [comment]
Maybe the API of fabric has been changed. This is the best inventory-about tool.

**Comment by panwolfram** [comment]
Yeah, multiple things in both Fabric and Minecraft itself changed. I've tried to update it to 1.17, but as I've never touched any Fabric mods, I've failed. As @badcodebuilder says, I also think that this mod is the best one out there. I can upload my changes if you'd like to, so we all can have a look at it.

**Comment by blackd** [comment]
I've made a pull request #57 with initial 1.17 support.

So far only the config screen is broken the rest works.  

However minecraft modding and kotlin are completely new thing for me so if someone can help I'll appreciate it.

**Comment by frozenwarrior41** [comment]
> Yeah, multiple things in both Fabric and Minecraft itself changed. I've tried to update it to 1.17, but as I've never touched any Fabric mods, I've failed. As @badcodebuilder says, I also think that this mod is the best one out there. I can upload my changes if you'd like to, so we all can have a look at it.



> I've made a pull request #57 with initial 1.17 support.
> 
> So far only the config screen is broken the rest works.
> 
> However minecraft modding and kotlin are completely new thing for me so if someone can help I'll appreciate it.

honestly Ive never done any sort of programming for anything, but if a few people would be interested in working around it getting this updated i know i wont be the only thankful person out there!

**Comment by blackd** [comment]
Well it's ready.... I think :)

you can grab a release from https://github.com/blackd/Inventory-Profiles/releases/tag/v0.7.0

**Comment by frozenwarrior41** [comment]
when i try to launch it idk why but this is what happens in my console just before is crashes

**A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: inventoryprofiles requires {fabric-screen-api-v1 @ [>=1.0.4]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)
	... 5 more
20:21:13.034

20:21:13.034
Process crashed with exit code 1**

**Comment by frozenwarrior41** [comment]
blackd you are a hero! if you can, link it to the one on Curseforge cause people have been asking about it!

**Comment by blackd** [comment]
Hi people,

I decided to fork the mod and publish it on https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next  (still under review I hope they will make it available soon)

**Comment by panwolfram** [comment]
@blackd, thank you so much! I've been trying to update this mod for hours - and your version works flawlessly! Now I can update my 1.15 server to a newest version :) Thank you once more!
